replicaCount: 1

image:
  repository: __AWS_ACCOUNT_ID__.dkr.ecr.eu-north-1.amazonaws.com/goit-devops-homework
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

django:
  config:
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432
    POSTGRES_DB: django
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

postgresql:
  host: "djangoapp-db.xxx.eu-north-1.rds.amazonaws.com"  # Will be populated after RDS creation
  port: "5432"
  database: "djangoapp"
  username: "postgres"
  password: "your-secure-password"  # Should match terraform variable