pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
    - name: git
      image: alpine/git
      command:
        - sleep
      args:
        - 99d
"""
    }
  }

  environment {
    AWS_ACCOUNT_ID = sh(script: 'aws sts get-caller-identity --query Account --output text', returnStdout: true).trim()
    ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.eu-north-1.amazonaws.com"
    IMAGE_NAME   = "goit-devops-homework"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"

    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            cd django
            /kaniko/executor \\
              --context `pwd` \\
              --dockerfile `pwd`/Dockerfile \\
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \\
              --cache=true \\
              --insecure \\
              --skip-tls-verify
          '''
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              export GITHUB_TOKEN=$GIT_PAT
              git clone https://$GIT_USERNAME:$GIT_PAT@github.com/v-kulyk/goit-devops-homework.git
              cd goit-devops-homework/final-project

              # Update image tag
              sed -i "s/tag: .*/tag: $IMAGE_TAG/" charts/django-app/values.yaml
              
              # Update AWS account ID placeholder
              sed -i "s/__AWS_ACCOUNT_ID__/$AWS_ACCOUNT_ID/g" charts/django-app/values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"
              git remote set-url origin https://${GIT_PAT}@github.com/v-kulyk/goit-devops-homework.git

              git add charts/django-app/values.yaml
              git commit -m "Update image tag to $IMAGE_TAG and ECR registry"

              export GIT_ASKPASS=/bin/echo
              git push -f origin main
            '''
          }
        }
      }
    }
  }
}